//ATENÇÃO AGENTE CUIDADO COM ESTE INDIVÍDUO
const idade = 32
const altura = 1.77
const peso = 65
const nome1 = "Volodomir"
const nome2 = "Kroshovet"
let filiação = "Spetnaz"
let statusDeVida = true
console.log("FICHA INDIVIDUAL")
console.log("Indivíduo de alta periculosidade denonimado", nome1, nome2, "possui", idade,
"anos e", altura, "de altura e pesa", peso, "quilogramas, é filiado aos", filiação, "russos", "situação de vida:", statusDeVida)  
