//ISSO É UMA REFERÊNCIA A JOJO?? 

const JoJo = "JOSEPH JOESTAR"
const idade = "IDADE SUFICIENTE PRA CHUTAR A TUA BUNDA"

console.log("SEGUINTE CHARÁ", "MEU NOME É", JoJo, "E EU TENHO", idade, "SEU MANÉ")

//SEGUINTE CHARÁ, MEU NOME É JOSEPH JOESTAR E EU TENHO IDADE SUFICIENTE PRA CHUTAR A TUA BUNDA, SEU MANÉ

